# This is a basic workflow to help you get started with Actions

name: Build project and deploy on local environment

# Controls when the action will run.
on:
  workflow_dispatch:
  inputs:
    name:
      description: 'Person to greet'
      required: true
      default: 'Mona the Octocat'
    home:
      description: 'location'
      required: false
      default: 'The Octoverse'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Set up java version
      - name: Set up jdk version
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # Build project
      - name: Build project with Maven
        run: mvn clean package -Dmaven.test.skip=true

      # Upload to local tomcat
      - name: Upload war to tomcat
        uses: garygrossgarten/github-action-scp@release
        with:
          local: 'target/dspace.war'
          remote: 'D:\software\tomcat9\webapps'
          host: ${{ secrets.LOCAL_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.LOCAL_PORT }}
